#!/bin/bash
#
# Copyright (c) 2011, Simon Howard
#
# Permission to use, copy, modify, and/or distribute this software
# for any purpose with or without fee is hereby granted, provided
# that the above copyright notice and this permission notice appear
# in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR
# CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
# NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
# CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
#
# Check the output of the lha tool matches the expected output given
# by the Unix LHA tool exactly.
#

set -eu

LHA_TOOL=lha
GATHER=false
#GATHER=true

test_archive() {
	archive=$1

	# Fix timestamp to a set date.  The list output includes
	# the timestamp of the file, so it must match the check
	# file.

	touch -d 2000-01-01 archives/$archive

	# Gather output from Unix LHA tool?

	if $GATHER; then
		if [ ! -e output/$archive-l.txt ]; then
			$LHA_TOOL l archives/$archive > output/$archive-l.txt
		fi

		if [ ! -e output/$archive-v.txt ]; then
			$LHA_TOOL v archives/$archive > output/$archive-v.txt
		fi
	fi

	# Normal list output:

	../src/lha l archives/$archive > /tmp/l.txt

	if ! diff -u /tmp/l.txt output/$archive-l.txt; then
		echo "Output not as expected for lha l $archive" >&2
	fi

	rm /tmp/l.txt

	# Verbose output:

	../src/lha v archives/$archive > /tmp/v.txt

	if ! diff -u /tmp/v.txt output/$archive-v.txt; then
		echo "Output not as expected for lha v $archive" >&2
	fi

	rm /tmp/v.txt
}

test_archive larc333/lz4.lzs
test_archive larc333/lz5.lzs
#test_archive larc333/sfx.com         TODO - sfx
test_archive larc333/subdir.lzs
test_archive larc333/long.lzs

test_archive lharc113/lh0.lzh
test_archive lharc113/lh1.lzh
#test_archive lharc113/sfx.com        TODO - sfx
test_archive lharc113/subdir.lzh
test_archive lharc113/long.lzh

test_archive lha213/lh0.lzh
test_archive lha213/lh5.lzh
#test_archive lha213/sfx.exe          TODO - sfx
test_archive lha213/subdir.lzh

test_archive lha255e/lh0.lzh
test_archive lha255e/lh5.lzh
#test_archive lha255e/sfx.exe         TODO - sfx
test_archive lha255e/subdir.lzh

test_archive lha_unix114i/lh0.lzh
test_archive lha_unix114i/lh5.lzh
test_archive lha_unix114i/lh6.lzh
test_archive lha_unix114i/lh7.lzh
test_archive lha_unix114i/subdir.lzh

test_archive lha_os2_208/example.lzh

test_archive pmarc2/pm0.pma
test_archive pmarc2/pm2.pma
test_archive pmarc2/comment.pma
#test_archive pmarc2/sfx.com          TODO - sfx

test_archive lha_amiga_122/level0.lzh
#test_archive lha_amiga_122/level1.lzh    TODO - Unix LHA fails
#test_archive lha_amiga_122/level2.lzh    TODO - Level 2 decode
test_archive lha_amiga_122/lh0.lzh
test_archive lha_amiga_122/lh1.lzh
test_archive lha_amiga_122/lh4_long.lzh
test_archive lha_amiga_122/lh4.lzh
test_archive lha_amiga_122/lh5.lzh
test_archive lha_amiga_122/subdir.lzh

test_archive lha_amiga_212/level0.lzh
test_archive lha_amiga_212/level1.lzh
#test_archive lha_amiga_212/level2.lzh   TODO - Level 2 decode
test_archive lha_amiga_212/lh1.lzh
test_archive lha_amiga_212/lh6.lzh

