#!/bin/bash
#
# Copyright (c) 2011, Simon Howard
#
# Permission to use, copy, modify, and/or distribute this software
# for any purpose with or without fee is hereby granted, provided
# that the above copyright notice and this permission notice appear
# in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR
# CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
# NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
# CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
#
# Check the output of the lha tool matches the expected output given
# by the Unix LHA tool exactly.
#

set -eu

LHA_TOOL=lha
GATHER=false
#GATHER=true

test_archive() {
	archive=$1

	# Gather output from Unix LHA tool?

	if $GATHER; then
		if [ ! -e output/$archive-t.txt ]; then
			$LHA_TOOL t archives/$archive > output/$archive-t.txt
		fi
	fi

	# CRC test:

	../src/lha t archives/$archive > /tmp/t.txt

	if ! diff -u output/$archive-t.txt /tmp/t.txt; then
		echo "Output not as expected for lha t $archive" >&2
		exit 1
	fi

	rm /tmp/t.txt
}

test_archive lengths/lh1-0.lzh
test_archive lengths/lh1-1.lzh
test_archive lengths/lh1-64k.lzh
test_archive lengths/lh1-1m.lzh
test_archive lengths/lh1-2m.lzh

