#!/bin/bash
#
# Copyright (c) 2011, Simon Howard
#
# Permission to use, copy, modify, and/or distribute this software
# for any purpose with or without fee is hereby granted, provided
# that the above copyright notice and this permission notice appear
# in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR
# CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
# NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
# CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
#
# Check the output of the lha tool matches the expected output given
# by the Unix LHA tool exactly.
#

set -eu

test_archive() {
	archive=$1

	../src/lha l archives/$archive > /tmp/l.txt
	diff -u /tmp/l.txt output/$archive-l.txt

	rm /tmp/l.txt

	../src/lha v archives/$archive > /tmp/v.txt
	diff -u /tmp/v.txt output/$archive-v.txt

	rm /tmp/v.txt
}

test_archive larc333/lz4.lzs
test_archive larc333/lz5.lzs
#test_archive larc333/sfx.com
test_archive larc333/subdir.lzs

test_archive lharc113/lh0.lzh
test_archive lharc113/lh1.lzh
#test_archive lharc113/sfx.com
test_archive lharc113/subdir.lzh

test_archive lha213/lh0.lzh
test_archive lha213/lh5.lzh
#test_archive lha213/sfx.exe
test_archive lha213/subdir.lzh

test_archive lha255e/lh0.lzh
test_archive lha255e/lh5.lzh
#test_archive lha255e/sfx.exe
test_archive lha255e/subdir.lzh

test_archive lha_unix114i/lh0.lzh
test_archive lha_unix114i/lh5.lzh
test_archive lha_unix114i/lh6.lzh
test_archive lha_unix114i/lh7.lzh
test_archive lha_unix114i/subdir.lzh

test_archive lha_os2_208/example.lzh

