#!/bin/bash
#
# Copyright (c) 2011, 2012, Simon Howard
#
# Permission to use, copy, modify, and/or distribute this software
# for any purpose with or without fee is hereby granted, provided
# that the above copyright notice and this permission notice appear
# in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR
# CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT,
# NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN
# CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
#
# Test script that uses the dump-headers tool to read the file
# headers from test archives and compares them to some known good
# values.
#

set -eu

test_archive() {
	archive=$1
	expected="output/$archive-hdr.txt"

	./dump-headers "archives/$archive" > /tmp/hdr.txt

	if [ ! -e "$expected" ]; then
		echo "New file: $expected"
		cp /tmp/hdr.txt "$expected"
		cat "$expected"
	fi

	if ! diff -u "$expected" /tmp/hdr.txt; then
		echo "Output not as expected for $archive" >&2
		exit 1
	fi
}

test_archive larc333/lz4.lzs
test_archive larc333/lz5.lzs
test_archive larc333/sfx.com
test_archive larc333/subdir.lzs
test_archive larc333/long.lzs

test_archive lharc113/lh0.lzh
test_archive lharc113/lh1.lzh
test_archive lharc113/sfx.com
test_archive lharc113/subdir.lzh
test_archive lharc113/long.lzh

test_archive lha213/lh0.lzh
test_archive lha213/lh5.lzh
test_archive lha213/lh5_long.lzh
test_archive lha213/sfx.exe
test_archive lha213/subdir.lzh

test_archive lha255e/lh0.lzh
test_archive lha255e/lh5.lzh
test_archive lha255e/sfx.exe
test_archive lha255e/subdir.lzh

test_archive lha_unix114i/lh0.lzh
test_archive lha_unix114i/lh5.lzh
test_archive lha_unix114i/lh6.lzh
test_archive lha_unix114i/lh6_long.lzh
test_archive lha_unix114i/lh7.lzh
test_archive lha_unix114i/lh7_long.lzh
test_archive lha_unix114i/subdir.lzh

test_archive lha_os2_208/lh0.lzh
test_archive lha_os2_208/lh5.lzh
test_archive lha_os2_208/lfn.lzh
test_archive lha_os2_208/subdir.lzh
test_archive lha_os2_208/lh1.lzh
test_archive lha_os2_208/h3_lfn.lzh
test_archive lha_os2_208/h3_lh0.lzh
test_archive lha_os2_208/h3_lh5.lzh
test_archive lha_os2_208/h3_subdir.lzh

test_archive pmarc2/pm0.pma
test_archive pmarc2/pm2.pma
test_archive pmarc2/comment.pma
test_archive pmarc2/sfx.com
test_archive pmarc2/long.pma

test_archive lha_amiga_122/level0.lzh
test_archive lha_amiga_122/level1.lzh
test_archive lha_amiga_122/level2.lzh
test_archive lha_amiga_122/lh0.lzh
test_archive lha_amiga_122/lh1.lzh
test_archive lha_amiga_122/lh4_long.lzh
test_archive lha_amiga_122/lh4.lzh
test_archive lha_amiga_122/lh5.lzh
test_archive lha_amiga_122/subdir.lzh
test_archive lha_amiga_122/sfx.run

test_archive lha_amiga_212/level0.lzh
test_archive lha_amiga_212/level1.lzh
test_archive lha_amiga_212/level2.lzh
test_archive lha_amiga_212/lh1.lzh
test_archive lha_amiga_212/lh6.lzh

test_archive lharc_atari_313a/lh0.lzh
test_archive lharc_atari_313a/lh5.lzh
test_archive lharc_atari_313a/lz5.lzh
test_archive lharc_atari_313a/subdir.lzh
test_archive lharc_atari_313a/sfx.tos
test_archive lharc_atari_313a/shorter.lzh
test_archive lharc_atari_313a/h1_lh5.lzh
test_archive lharc_atari_313a/h1_lz5.lzh
test_archive lharc_atari_313a/h1_subdir.lzh
test_archive lharc_atari_313a/h2_lh5.lzh
test_archive lharc_atari_313a/h2_lz5.lzh
test_archive lharc_atari_313a/h2_subdir.lzh

test_archive lha_x68k_213/h0_lh0.lzh
test_archive lha_x68k_213/h0_lh5.lzh
test_archive lha_x68k_213/h0_subdir.lzh
test_archive lha_x68k_213/h1_lh0.lzh
test_archive lha_x68k_213/h1_lh5.lzh
test_archive lha_x68k_213/h1_subdir.lzh
test_archive lha_x68k_213/h2_lh0.lzh
test_archive lha_x68k_213/h2_lh5.lzh
test_archive lha_x68k_213/h2_subdir.lzh
test_archive lha_x68k_213/sfx.x

test_archive maclha_224/l0_lh0.lzh
test_archive maclha_224/l0_lh1.lzh
test_archive maclha_224/l0_lh5.lzh
test_archive maclha_224/l0_nm_lh5.lzh
test_archive maclha_224/l1_full_subdir.lzh
test_archive maclha_224/l1_lh0.lzh
test_archive maclha_224/l1_lh1.lzh
test_archive maclha_224/l1_lh5.lzh
test_archive maclha_224/l1_nm_lh5.lzh
test_archive maclha_224/l1_subdir.lzh
test_archive maclha_224/l2_full_subdir.lzh
test_archive maclha_224/l2_lh0.lzh
test_archive maclha_224/l2_lh1.lzh
test_archive maclha_224/l2_lh5.lzh
test_archive maclha_224/l2_nm_lh5.lzh
test_archive maclha_224/l2_subdir.lzh

test_archive regression/abspath.lzh
test_archive regression/badterm.lzh

test_archive generated/lzs/lzs.lzs
test_archive generated/lzs/long.lzs

